# 1. Connect to docekr - qa
server.port=8004
eureka.client.service-url.defaultZone=http://discovery-servery:8761/eureka
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# 2. circuit breaker config
#resilience4j.circuitbreaker.instances.customerServiceBreaker.sliding-window-size=5
#resilience4j.circuitbreaker.instances.customerServiceBreaker.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.customerServiceBreaker.wait-duration-in-open-state=10s
#
#eureka.instance.prefer-ip-address=true

# 1. Tell Micrometer to record 100% of all requests (1.0 = 100%)
# (In production, companies usually set this to 0.1 so they only record 10% to save memory)
#management.tracing.sampling.probability=1.0

# 2. Tell the services where the Zipkin Docker container lives
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# CORRECT FOR DOCKER