# ===============================
# PROD ENVIRONMENT (AWS Cloud)
# ===============================

# AWS RDS Database

#spring.datasource.url=jdbc:mysql://ecommerce-cloud-db.c6lgkoeyyyz9.us-east-1.rds.amazonaws.com:3306/customer_service?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://ecommerce-cloud-db.c6lgkoeyyyz9.us-east-1.rds.amazonaws.com:3306/customer_service
spring.datasource.username=admin
spring.datasource.password=AdminPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# AWS Docker Network Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
