spring.data.redis.host=localhost
spring.data.redis.port=6379

# 1. Connect to Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 2. Enable Actuator so we can see the routes in the browser
management.endpoints.web.exposure.include=gateway,health

# 3. Enable Discovery (Let Gateway see CUSTOMER-SERVICE)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE

# 4. Define the Manual Route for Customer Service
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/customer/**
spring.cloud.gateway.server.webflux.routes[0].filters[0] = AuthenticationFilter


spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=3
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userIpKeyResolver}
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter


spring.cloud.gateway.server.webflux.routes[2].id=Order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=AuthenticationFilter
spring.cloud.gateway.server.webflux.routes[2].filters[1]=AddRequestHeader=X-Gateway-Secret, MySuperSecretPassword123!

spring.cloud.gateway.server.webflux.routes[3].id=Product
spring.cloud.gateway.server.webflux.routes[3].uri=lb://PRODUCT
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/category/**

spring.cloud.gateway.server.webflux.routes[4].id=payment
spring.cloud.gateway.server.webflux.routes[4].uri=lb://PAYMENT
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/payment/**


# 1. Tell Micrometer to record 100% of all requests (1.0 = 100%)
# (In production, companies usually set this to 0.1 so they only record 10% to save memory)
management.tracing.sampling.probability=1.0

# 2. Tell the services where the Zipkin Docker container lives
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Force the service to register with Eureka using an IP address, not a hostname
eureka.instance.prefer-ip-address=true


