# Universal Settings

server.port=8002
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.instance.prefer-ip-address=true

# These are standard settings for sending/receiving text/json
spring.kafka.consumer.group-id=my-group-id
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=orderConfirmation:com.order.kafka.OrderConfirmation


#circuit breaker
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.prodcut-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.prodcut-service.permitted-number-of-calls-in-half-open-state=3

#retry
resilience4j.retry.instances.product-service.max-attempts=3
resilience4j.retry.instances.product-service.enable-exponential-backoff=true
resilience4j.retry.instances.prodcut-service.wait-duration=2s

resilience4j.circuitbreaker.instances.payment.sliding-window-size=5
resilience4j.circuitbreaker.instances.payment.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.payment.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.payment.permitted-number-of-calls-in-half-open-state=3

#retry
resilience4j.retry.instances.payment.max-attempts=3
resilience4j.retry.instances.payment.enable-exponential-backoff=true
resilience4j.retry.instances.payment.wait-duration=2s