# AWS S3 storage configuration
#spring.profiles.active=prod

# AWS S3 bucket details
storage.s3.bucket-name=product-image-s3
spring.cloud.aws.region.static=ap-south-1
spring.cloud.aws.credentials.access-key=AKIAU6GDWVAIWWQAMC6M
spring.cloud.aws.credentials.secret-key=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