spring.application.name=Notification-Service
server.port=8004

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nishantkalia71001@gmail.com
spring.mail.password=ffla rhxq bgxx brkp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.datasource.url=jdbc:mysql://localhost:3306/notification_service
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



# 1. Where is Kafka?
spring.kafka.bootstrap-servers=localhost:9092

# 2. Who am I? (Group ID)
# This ID groups your notification instances together.
spring.kafka.consumer.group-id=notification-group

# 3. How to read the data? (Deserializers)
# The Key is a simple String (Order Reference usually)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# The Value is the complex JSON object (OrderConfirmation)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# 4. JSON Security (CRITICAL)
# By default, Spring Kafka blocks unknown packages for security.
# The OrderConfirmation came from 'com.example.orderservice...', but here it is 'com.Notification_Service...'.
# The '*' tells Spring: "Trust any object you find, just try to map it."
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.type.mapping=com.order.kafka.OrderConfirmation:com.Notification_Service.order.OrderConfirmation


# 5. Offset Reset
# "earliest" means: If I crash and restart, or if I am new, read missed messages from the beginning.
spring.kafka.consumer.auto-offset-reset=earliest
