spring.application.name=config-server
# industry standard port for config server
server.port=8888
# this point directly go to the local voult you just committed
spring.cloud.config.server.git.uri=file:///D:/STS/SPRING_PROJECT/E-CommerceBackend/config-repo

# 1. Tell Config Server to read raw files, NOT Git!
#spring.profiles.active=native

# 2. Give it the EXACT Windows path to your folder. 
# (Make sure to use forward slashes '/', and add 'file:///' at the front)
#spring.cloud.config.server.native.search-locations=file:///D:/STS/SPRING_PROJECT/E-CommerceBackend/config-repo

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


